title: Halfwhit Hacks
description: "Halfwhit's Personal Blog"
author:
  name: "Halfwhit"
  email: "halfwhit@gmail.com"
  url: "https://halfwhit.uk"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
    values:
      lang: en_GB
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Halfwhit"
year : "2024"
