#+title: Learning To Learn
#+options: toc:nil num:nil
#+begin_export html
---
layout: post
title: Learning to Learn
excerpt: A blog post about developing a robust learning methodology/process
---
#+end_export
I never used to particularly enjoy the process of learning back at school; the pacing didn't suit me, I was easily distracted and for the majority of subjects just wasn't interested. Since growing into an adult shape, I have identified that I actually *love* learning, now that I have the freedom to follow my own interests and threads of knowledge.

The turning point for myself was when I was signed off work for the best part of a year, and decided to return to University to help me change careers into something computer science related. The path I took through my course hasn't been as linear as many people's experience, switching from full time study to part time after landing my first job in the field: An IT technician in a somewhat large secondary school.

Over the last 5 years, having entered the field I began to look around at the vastness of possibilities within IT with the original intention of becoming a software engineer. It wasn't until I decided that I wanted to know more about how the internet *actually* worked and read through the majority of the book [[https://gaia.cs.umass.edu/kurose_ross/about.php][Computer Networking: A Top Down Approach]] as a bit of light reading that synapses started firing off and making new connections of thought, bringing unexpected emotional and motivational feelings with the experience. Ever since this, I have effectively been chasing the dragon, following my own pursuit of knowledge towards a career in penetration testing.

A while ago I discovered the "Slip-box" or "Zettlekasten" method employed famously by [[https://en.wikipedia.org/wiki/Niklas_Luhmann][Niklas Luhmann]], and attempted to use the technique to make lecture notes and write an assignment, which now on reflection seemed to work well (though who knows with confirmation bias, plus it was a subject I was genuinely interested in: penetration testing). After the relief of finishing the course modules and assignments my second brain laid dormant without ingesting any additional notes, even fleeting ones (see Zettlekasten methodology).

I want to change this. I want to add to my second brain, I want to develop new thoughts and nurture my intrigue to find new interesting things that can fit in with my accumulated knowledge and skills. I want to be an expert, and not just remember things because I know I will be tested on the subject. So I bought a book (How to take Smart Notes) and setup my tools and workflow.

I quite like the writing process, even though I admittedly do very little of it (just look at how empty this blog is!). I equally quite like reading, though never seem to find the time to read anything: this needs to change, and I have found that the simple act of bringing my Kindle to my lunchbreak gives be a solid hour of uninterrupted (yeah, right!) time to just read and think, or write (which is just thinking with a pen and having a discussion with yourself and your notes). My workflow here is far from perfect, and the very act of me writing the draft paragraphs of this ~~essay~~ blog post is helping me to refine upon it, through the feedback provided by getting my **own** thoughts on paper.

Half of what I write here will be scrapped. More, probably after reading over what I have so far! But simply trying to explain my process, why I am doing it, and how it works definitely *feels* like I am just scratching the surface of what could become a fun and productive past time. I really enjoy reading the well constructed posts that get submitted to aggregate sites such as Hacker News, and have only just made the connection that I should keep a reference of posts that I found interesting to incorporate in future work. So thank you to all of you interesting people out there, hopefully one day I will write something of interest for you to one day read.
