#+title: Halfwhit Hacks
#+begin_export html
---
layout: page
title: Hello World!
---
#+end_export
* Welcome

I am Halfwhit, and this is my personal blog. I've been toying with the idea of using blogging to help organise myself, my life, and my thoughts in addition to building out a zettlekasten inspired knowledge database.

I have a few goals throughout this endeavour, all that are closely linked. I intend to document my journey in *regular* blog posts. I'll try to keep this initial entry updated with my goals, and maybe give a bit of a retrospective if I feel my goals have been achieved.

* Goals

- Become familiar with vim
- Learn, live and breathe emacs in evil mode
- Begin using org-mode and org-agenda to organise my work and personal life
- Build out a knowledge database using org-roam
- Construct a post-installation script for Arch Linux to set up my system with my preffered settings
- Convert the post installation script into a customised, bootable ISO using ArchISO
- Blog about penetration testing techniques, tactics, and maybe even some procedures

* Inspiration

A lot of the content I plan to cover in this blog is inspired by the fantastic Linux content creators out there, most notably [[https://youtube.com/c/DistroTube][DistroTube]] and [[https://youtube.com/c/SystemCrafters][System Crafters]].

* Links

+ [[https://github.com/Halfwhit][Halfwhit's GitHub]]
+ [[https://github.com/Halfwhit/halfwhit.github.io][This site on GitHub]]
